# -*- coding: utf-8 -*-
"""1-3 Interação com usuário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKjWEZ5pKU0xPsJTMvpJn7imTN0O8jrr

##Visualização de Variáveis e textos
"""

print("conhecendo o comando Print em Python")
x = 8
print(x)

y = 10
Soma = x + y
print(Soma)

nome = "Bruno Silveira"
print(nome)

"""##Concatenação

"""

x = 5
print("O valor de x é", x)

print("O valor de x é", x, "e o dobro é", x* 2)

print("Eu", nome, "tirou", x, "na prova de Phyton")

y = 10; z = 20 + x - y
print("Declarar várias variáveis na mesma linha:", y, z)

"""##Type"""

x = 10
type(x)
print("x", type(x))
nome = "Bruno"
print("nome", type(nome))

num = "100"
num_convertido = int(num) #converter variável
print("num", type(num))
print("num_convertido", type(num_convertido))

num_float = float(num)
print("num_float", type(num_float))

"""##Input





*   Armazenar a informação digitada pelo usuário em uma variável
*   O dado armazenado sempre será um texto




"""

Nome = input("Digite o nome do usuário:") #Aguarda o usuário digitar algo
print("Olá", Nome)

Valor = input("Digite a nota: ")
print("O valor digitado foi", Valor)

valor = "100.50"  # Exemplo de valor como string
valor_float = float(valor)  # Converter para float
Desconto = valor_float * 5.0 / 100  # Calcular o desconto
print("O valor do desconto é", Desconto)