# -*- coding: utf-8 -*-
"""Estrutura Condicional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0pNtU-l1FPP_eSO-d_85fXq-fES2TCg

##Condicional
"""

# if

if 5>10:
  print("verdadero")

# if/else
num1 = 10
num2 = 5
if num1 > num2:
  print("O num1 é o maior numero")
else:
  print("O num2 é o maior numero")

# if/elif/else
num1 = 50
num2 = 10
if num1 > num2:
  print("O num1 é o maior numero")
elif num1 < num2:
  print("O num2 é o maior numero")
else:
    print("Os numeros são iguais")

"""##Condicional com operadores lógicos"""

num1 = 10
num2 = 5
num3 = 20

if(num1 > num2) and (num1 > num3):
  print("O num1 é o maior numero")
else:
  print("O num1 não é o maior numero")